# Generated by Django 2.1.5 on 2020-05-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('id',), 'verbose_name_plural': 'To do'},
        ),
    ]
